# Generated by Django 5.1 on 2024-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_reportelement_order_alter_reportelement_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "filter_column",
                    models.CharField(
                        help_text="Filter based on this column's data.", max_length=3
                    ),
                ),
                (
                    "filter_data",
                    models.CharField(
                        help_text="Rows where the above column contains this data will be used in the report.",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
