# Generated by Django 5.1 on 2024-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_reportfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportelement",
            name="emphasized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reportelement",
            name="large",
            field=models.BooleanField(default=False),
        ),
    ]
