# Generated by Django 5.1 on 2024-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_reportelement_emphasized_reportelement_large"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportelement",
            options={"ordering": ("order",)},
        ),
        migrations.AlterField(
            model_name="reportelement",
            name="element_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
